// ResultsView.swift
// NutriFacts

import SwiftUI

/// Displays nutrition facts after a successful AI lookup.
/// Contains a segmented tab picker switching between OverviewTabView and DetailsTabView.
/// A disclaimer footnote and unit label ("per 100g" / "per 100ml") appear on both tabs.
struct ResultsView: View {

    let nutritionFacts: NutritionFacts

    @State private var selectedTab: ResultsTabSelection = ResultsTabSelection.defaultTab

    var body: some View {
        VStack(spacing: 0) {
            tabPicker
                .padding(.horizontal, 16)
                .padding(.top, 12)

            unitLabel
                .padding(.top, 8)

            tabContent
                .padding(.top, 8)

            Spacer()

            disclaimerFootnote
                .padding(.horizontal, 16)
                .padding(.bottom, 12)
        }
        .navigationTitle(nutritionFacts.productName)
        .navigationBarTitleDisplayMode(.inline)
    }

    // MARK: - Subviews

    private var tabPicker: some View {
        Picker("Results tab", selection: $selectedTab) {
            ForEach(ResultsTabSelection.allCases, id: \.self) { tab in
                Text(tab.tabTitle).tag(tab)
            }
        }
        .pickerStyle(.segmented)
    }

    private var unitLabel: some View {
        Text(nutritionFacts.unitLabel)
            .font(.subheadline)
            .foregroundStyle(ThemeColor.secondaryLabel)
    }

    @ViewBuilder
    private var tabContent: some View {
        switch selectedTab {
        case .overview:
            OverviewTabView(nutritionFacts: nutritionFacts)
        case .fullDetails:
            DetailsTabView(nutritionFacts: nutritionFacts)
        }
    }

    private var disclaimerFootnote: some View {
        // swiftlint:disable:next line_length
        Text("Nutrition data is generated by AI and is intended for general informational purposes only. Values are approximate and may not reflect the exact composition of a specific product or brand. This app is not a medical device. Always consult a healthcare professional for dietary advice.")
            .font(.caption2)
            .foregroundStyle(ThemeColor.secondaryLabel)
            .multilineTextAlignment(.center)
    }
}

#Preview {
    NavigationStack {
        ResultsView(nutritionFacts: NutritionFacts(
            productName: "Apple",
            isLiquid: false,
            macronutrients: Macronutrients(
                calories: 52, totalFat: 0.2, saturatedFat: 0.0,
                transFat: 0.0, carbohydrates: 14, sugar: 10,
                dietaryFiber: 2.4, protein: 0.3
            ),
            vitamins: [
                NutrientItem(id: UUID(), nutrientName: "Vitamin C", nutrientAmount: 5.1, nutrientUnit: "mg")
            ],
            minerals: [
                NutrientItem(id: UUID(), nutrientName: "Potassium", nutrientAmount: 107, nutrientUnit: "mg")
            ],
            allergens: [],
            ingredients: "Water, apple concentrate."
        ))
    }
}
